### ISSUE TITLE
[BUG] Media Query Problems

### ISSUE THREAD

**Issue by BrianMorse12604** [cse110-sp24-group2/cse110-sp24-group2#153]
**Is your feature request related to a problem? Please describe.**

When you are at a weird size, the days of the week disappear along with some of the days, see screenshot for details. Need to fix media query so that this does not happen

![image](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/122561802/296aad56-2e05-4eb7-b95e-225ed491b721)

**Describe the solution you'd like**

**Additional context**

**Comment by udsingla** [comment]
![Screenshot 2024-06-04 175025](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/130015308/caa3c30e-3a19-47e1-9261-849b89a1074b)


This is how it looks on phone so make sure to fix the search bar size accordingly and also to fit the calendar in the width. The device I selected was iphone 14 pro max if you want to recreate it.
