### ISSUE TITLE
[DOCS] Ensure that filter page wireframe is up to date

### ISSUE THREAD

**Issue by WishingWell13** [cse110-sp24-group2/cse110-sp24-group2#196]
**Is your feature request related to a problem? Please describe.**

Make sure there is a wireframe of the filter page on the miro board

**Describe the solution you'd like**

**Additional context**

https://miro.com/app/board/uXjVKNpdRwE=/

**Comment by clarissacheng** [comment]
Finished wireframe for Search Page
