### ISSUE TITLE
[FEATURE] Create user flow diagram for our app

### ISSUE THREAD

**Issue by WishingWell13** [cse110-sp24-group2/cse110-sp24-group2#25]
**Is your feature request related to a problem? Please describe.**

Create a user flow diagram for our application using Draw.io or Miro

**Describe the solution you'd like**

**Additional context**

Similar to this lab: https://canvas.ucsd.edu/courses/54609/assignments/778838

**Comment by udsingla** [comment]
I created the UML user flowchart and added it on Miro Board please review it.

**Comment by vihsiao** [comment]
just want to confirm, when an arrow points to another arrow, does this mean that multiple operations return to one stage?

![image](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/114203025/87ff428c-89a6-421b-aea8-9892a72f3e46)

**Comment by udsingla** [comment]
Yes It means that the arrow transitions and follows that arrow. I did that to keep it cleaner otherwise it would have gotten too cluttered.

**Comment by vihsiao** [comment]
looks good 👍
