### ISSUE TITLE
[FEATURE] Incorporate strikeout and deletion of to-do list item

### ISSUE THREAD

**Issue by BrianMorse12604** [cse110-sp24-group2/cse110-sp24-group2#32]
**Is your feature request related to a problem? Please describe.**

Need the interactivity within each item to be marked as completed or removed if no longer necessary

**Describe the solution you'd like**

When the checkbox is marked, the text should have been struck through and when the x button is clicked, the item should be completely removed from the list

**Additional context**

**Comment by WishingWell13** [comment]
Implemented deletion with single click and strikedown
