### ISSUE TITLE
[REFACTOR] Calendar Colors Not Following DRY

### ISSUE THREAD

**Issue by WishingWell13** [cse110-sp24-group2/cse110-sp24-group2#74]
**Is your feature request related to a problem? Please describe.**

`calendar-script.js`  and `search-bar.js` define the colors of the calendar month twice. To support DRY code, we should reduce this repetition 

![image](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/54158686/58a0a741-3741-41ea-a16d-411fa2374ed5)

![image](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/54158686/87b4cdd2-ef5c-43de-b505-bf377516253a)

![image](https://github.com/cse110-sp24-group2/cse110-sp24-group2/assets/54158686/bccfd46f-09ec-4da6-9a79-a44304683af9)

**Describe the solution you'd like**

**Additional context**

**Comment by madhoolikacvss** [comment]
Added this issue to branch 37, the issue is dealth with there.

**Comment by WishingWell13** [comment]
Since branch 37 is no longer used, is this still fixed?

**Comment by WishingWell13** [comment]
Moved the search bar to the calendar, so now is a non-issue / resolved
